### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by UCC-team** [axzml/CSDNExporter#1]
article_url='https://blog.csdn.net/shimazhuge/article/details/105227229'

Traceback (most recent call last):
  File "main.py", line 167, in <module>
    to_pdf=args.to_pdf)
  File "main.py", line 133, in download_csdn_single_page
    title = soup.find_all('h1', {'class': 'title-article'})[0].string  ## 使用 html 的 title 作为 md 文件名
IndexError: list index out of range

**Comment by Eunice-grow** [comment]
解决了嘛

**Comment by axzml** [comment]
之所以出现这个问题, 是因为使用 requests.get(url) 无法直接请求 csdn 网站了, 没有返回正确的结果. 可以尝试使用 httpx 库, 或者研究下如何使用 requests 请求 csdn 网站. 这个代码我没时间维护了,  见谅~

**Comment by axzml** [comment]
OK 重新更新代码, 应该可以使用了, 安装 httpx 库

**Comment by Eunice-grow** [comment]
收到

**Comment by axzml** [comment]
> article_url='https://blog.csdn.net/shimazhuge/article/details/105227229'
> 
> Traceback (most recent call last): File "main.py", line 167, in to_pdf=args.to_pdf) File "main.py", line 133, in download_csdn_single_page title = soup.find_all('h1', {'class': 'title-article'})[0].string ## 使用 html 的 title 作为 md 文件名 IndexError: list index out of range
