### ISSUE TITLE
markdown 中的代码格式问题

### ISSUE THREAD

**Issue by ZeyuDong1** [axzml/CSDNExporter#10]
在markdown中，```没有换行，导致代码块错误分割
如图，```没有换行而是直接放在了最后一行代码的末尾，所以从第一个```python往后的内容都被认为是代码块内的内容。不清楚是否所有的markdown编辑器都这样，我这里两个markdown编辑器都会导致这种情况
![image](https://github.com/axzml/CSDNExporter/assets/79103838/8647a2d8-4b17-4387-b194-f9be064d4ba1)

**Comment by c4tovo** [comment]
update code utils.py in line 70
`soup.contents.append(NavigableString('```\n'))`
to 
`soup.contents.append(NavigableString('\n```\n'))`

**Comment by axzml** [comment]
![image](https://github.com/axzml/CSDNExporter/assets/16320631/742ac17f-92c9-468d-9d85-ec92a7d4b231)

**Comment by axzml** [comment]
我在自己电脑上测试是没有问题的，如下图。如果有问题，就按照 @c4tovo 的说明修改一下相应的代码吧：

![image](https://github.com/axzml/CSDNExporter/assets/16320631/8a4fe10b-1181-4c2b-8d51-67a930c786da)
